version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "sleep 10 && python manage.py makemigrations &&
        python manage.py migrate &&
        echo 'from django.contrib.auth.models import User; User.objects.create_superuser(username=\"admin\", email=\"admin@example.com\", password=\"admin\")' | python manage.py shell &&
        python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
